apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test
  region: ap-northeast-2
  version: "1.18"
vpc:
  id: ${vpcId}
  subnets:
    private:
      ap-northeast-2a: { id: '${subnetId' }
      ap-northeast-2c: { id: '${subnetId' }
    public:
      ap-northeast-2a: { id: '${subnetId' }
      ap-northeast-2c: { id: '${subnetId' }
  clusterEndpoints:
    publicAccess: true
    privateAccess: true