apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test
  region: ap-northeast-2
managedNodeGroups:
  - name: worker
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 10
    volumeType: gp3 # optional
    instanceType: t3.large
    privateNetworking: true
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
    tags:
      'team': 'devops'